spring:
  profiles:
    active: local
    group:
      local: common
      prod: common

---
spring:
  config:
    activate:
      on-profile: common

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  token-validity-in-milliseconds: ${JWT_TOKEN_VALIDITY}

cors:
  allowed-origins:
    - ${CORS_ALLOWED_ORIGINS}

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: ${DB_URL}?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
  jpa:
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false
